.PHONY: clean All

All:
	@echo "----------Building project:[ UOCoworking - Debug ]----------"
	@cd "UOCoworking" && "$(MAKE)" -f  "UOCoworking.mk"
clean:
	@echo "----------Cleaning project:[ UOCoworking - Debug ]----------"
	@cd "UOCoworking" && "$(MAKE)" -f  "UOCoworking.mk" clean
